sonar.projectKey=human-mobility-backend
sonar.projectName=HumanMobility Backend
sonar.organization=REEMPLAZAR_CON_TU_ORG_KEY

sonar.sources=src
sonar.exclusions=**/*.spec.ts,src/main.ts,**/*.module.ts,**/*.entity.ts,**/*.dto.ts,**/*.decorator.ts,**/node_modules/**

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
